kubectl: true
cloudflare: true
node: true
digitalocean: true
google: false
spotify: false
slack: false
jira: false
terraform: true
git: true
code: true
code_extensions: true
gnome: false
grub: false
golang: true
gitlab: true
uber: false
az: false