kubectl: true
cloudflare: false
node: true
digitalocean: false
google: false
spotify: false
slack: false
jira: false
terraform: true
git: true
code: false
code_extensions: false
gnome: flase
grub: false
golang: true
gitlab: true
github: false
azure: false
