kubectl: true
cloudflare: true
node: true
digitalocean: true
google: true
spotify: true
slack: true
jira: true
terraform: true
git: true
code: true
code_extensions: true
gnome: true
grub: true
golang: true
gitlab: true
uber: false
