kubectl: true
cloudflare: true
node: true
digitalocean: true
google: true
spotify: false
slack: true
jira: false
terraform: true
git: true
code: true
code_extensions: true
gnome: true
grub: false
golang: true
gitlab: true
github: true
azure: false
