#!/bin/bash -eux

ergodox_kernel='''
# Teensy rules for the Ergodox EZ Original / Shine / Glow
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789A]?", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789ABCD]?", MODE:="0666"
KERNEL=="ttyACM*", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", MODE:="0666"

# STM32 rules for the Planck EZ Standard / Glow
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", \
    MODE:="0666", \
    SYMLINK+="stm32_dfu"
'''

function github_release {
    curl -sL https://api.github.com/repos/$1/releases/latest | jq -r '.assets[].browser_download_url' | grep amd64 | grep $2 | grep -v musl | grep -v sha256
}

function install_debian {
    gopass_apt="/etc/apt/sources.list.d/gopass.list"
    if [ ! -f "$gopass_apt" ]
    then
        wget -q -O- https://api.bintray.com/orgs/gopasspw/keys/gpg/public.key | sudo apt-key add -
        echo "deb https://dl.bintray.com/gopasspw/gopass trusty main" | sudo tee $gopass_apt
    fi
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y \
        silversearcher-ag \
        most \
        jq \
        python3 \
        python3-pip \
        python3-dev \
        python3-setuptools \
        ruby \
        ruby-dev \
        rng-tools \
        gnupg \
        gopass \
        peco \
        neovim \
        zsh \
        terminator \
        git-crypt \
        git-lfs \
        chrome-gnome-shell \
        autojump \
        trash-cli \
        libncursesw5 \
        gtk+3.0 \
        webkit2gtk-4.0 \
        libusb-dev \
        inkscape \
        x11-apps \
        openvpn \
        docker \
        curl \
        xclip
        # nodejs

    # curl -L https://npmjs.org/install.sh | sudo sh
    wally_kernel=/etc/udev/rules.d/50-wally.rules
    sudo echo $ergodox_kernel > $wally_kernel
    curl -L --output ~/bin/wally https://configure.ergodox-ez.com/wally/linux
    # for package in yaml-cli quote-cli
    # do
    #     sudo npm install -g $package
    # done
    # sudo chown -R $USER:$(id -gn $USER) /home/mlodzikos/.config
    # dpkg
    (
        cd /tmp
        for repo in "sharkdp/fd" "sharkdp/bat" "MitMaro/git-interactive-rebase-tool"
        do
                name="$(echo $repo | cut -d'/' -f 2)"
                curl -L --output "$name.deb" $(github_release $repo 'deb')
                sudo dpkg -i "$name.deb"
                rm "$name.deb"
        done
        for packet in https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.0-amd64.deb https://zoom.us/client/latest/zoom_amd64.deb
        do
            name="$(echo $packet | rev | cut -d'/' -f 1 | rev)"
            curl -L --output "$name.deb" "${packet}"
            sudo dpkg -i "$name.deb"
            rm "$name.deb"
        done
    )

    # snap
    for app in code; do
        if ! snap list | grep "${app}"
        then
            snap install --classic "${app}"
        fi
    done
    for app in spotify; do
        if ! snap list | grep "${app}"
        then
            snap install "${app}"
        fi
    done
    for app in tre; do
        if ! snap list | grep "${app}"
        then
            snap install --devmode --beta "${app}"
        fi
    done
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/KaizIqbal/Bibata_Cursor/master/Bibata.sh)"
}

function install_osx {
    if ! brew --version
    then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    for p in the_silver_searcher jq gnupg2 gopass pinentry-mac peco bat neovim zsh git-crypt git-lfs fd autojump python trash-cli libusb zsh
    do
        brew install $p
    done
    echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf
    (
        cd /tmp
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py
        rm get-pip.py
    )
}

function install_fonts {
    (
        if [ ! -d "${FONT_DIR}" ]
        then
            mkdir -p "${FONT_DIR}"
        fi
        cd "${FONT_DIR}"
        for font in "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf" "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Mono.ttf" "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf"
        do
            font_name="$(echo "${font}" | rev | cut -d'/' -f1 | rev | sed 's|%20| |g')"
            if [ ! -f "$font_name" ]; then
                curl -fL --output "${font_name}" "${font}"
            fi
        done
        fc-cache -vf
        mkfontscale
        mkfontdir
    )
}

if apt-get --version &> /dev/null; then
    export FONT_DIR="$HOME/.local/share/fonts"
    export platform=linux
    install_debian
elif uname -a | grep -iq darwin; then
    export FONT_DIR="$HOME/Library/Fonts"
    export platform=darwin
    install_osx
fi

if [ ! -d "$HOME/.zplug" ]; then
    git clone --depth=1 https://github.com/zplug/zplug ~/.zplug
fi

if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

install_fonts

curl -L --output ~/bin/yaml2json "$(github_release wakeful/yaml2json $platform)"
curl -L "$(github_release 'minamijoyo/tfschema' $platform)" | tar -xz -C ~/bin


for gem in colorls lolcat
do
    if ! eval "$gem --version"
    then
        gem install --user $gem
    else
        gem update --user $gem
    fi
done

curl https://raw.githubusercontent.com/athityakumar/colorls/master/zsh/_colorls  > "$PWD/zsh/fpath/_colorls"

export CLOUDSDK_CORE_DISABLE_PROMPTS=1
if ! gcloud version
then
    curl https://sdk.cloud.google.com | bash
else
    gcloud components update
fi

curl -L https://cht.sh/:cht.sh > ~/bin/cht.sh
curl -L https://raw.githubusercontent.com/kamranahmedse/git-standup/master/installer.sh | sudo sh
curl -o ~/bin/git-hooks https://raw.githubusercontent.com/icefox/git-hooks/master/git-hooks
curl -L git.io/trans -o ~/bin/trans
gopass completion zsh > "$PWD/zsh/fpath/_gopass"
chmod -x ~/bin/*

for repo in "syndbg/goenv" "tfutils/tfenv"
do
    location="$HOME/.$(echo $repo | cut -d'/' -f 2)"
    if [ ! -d "$location" ]
    then
        git clone --branch master --depth 1 https://github.com/$repo.git "$location"
    else
        (
            cd "$location"
            git pull
        )
    fi
done
