#!/bin/bash
set -e
git_action=0

function move_cache_to_config {
    local config_name config_directory
    config_name="$1"
    config_localization="$2"
    if [ -a ".commit-cache-${config_name}" ]; then
        mv ".commit-cache-${config_name}" "${config_localization}"
        git add "${config_localization}"
        git_action=1
    fi

}

function main {
    move_cache_to_config "vscode" "provisioning/vscode/installed_vs_extensions"
    move_cache_to_config "gitconfig" "provisioning/git/.gitconfig"
    if [ "$git_action" -eq 1 ]; then
        git commit --amend -C HEAD --no-verify
    fi
}
main > /dev/null
exit