#!/bin/bash
set -e
git_action=0

function move_cache_to_config {
    local config_name config_localization
    config_name="$1"
    config_localization="$2"
    if [ -a ".commit-cache-${config_name}" ]; then
        mv ".commit-cache-${config_name}" "${config_localization}"
        CHANGED=`git diff HEAD@{1} --stat -- "${config_localization}" | wc -l`
        if [ $CHANGED -gt 0 ]; then
            git add "${config_localization}"
            git_action=1
        fi
    fi
}

function main {
    move_cache_to_config "vscode" "vscode/installed_vs_extensions"
    if [ "$git_action" -eq 1 ]; then
        git commit --amend --no-edit -C HEAD --no-verify
    fi
}
main
exit